# Generated by Django 2.2 on 2020-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='Category',
            field=models.ManyToManyField(to='ecommerce.Category'),
        ),
    ]
