# Generated by Django 2.2 on 2021-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('T', 'Toyota'), ('N', 'Nissan'), ('BB', 'Benz'), ('B', 'BMW')], max_length=1),
        ),
    ]
