# Generated by Django 2.2 on 2020-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='ecommerce.OrderItem'),
        ),
    ]
