# Generated by Django 2.2 on 2019-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('n', 'Not available'), ('r', 'Reserved')], default='m', max_length=1),
        ),
    ]
