# Generated by Django 2.2 on 2019-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20190930_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('n', 'Not available'), ('r', 'Reserved')], default='a', max_length=1),
        ),
    ]
