# Generated by Django 2.2 on 2019-10-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20191001_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not available'), ('R', 'Reserved')], max_length=50),
        ),
    ]
