# Generated by Django 2.2 on 2019-10-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20191001_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available'), ('Reserved', 'Reserved')], max_length=50),
        ),
    ]
