# Generated by Django 2.2 on 2019-10-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_item_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quality',
        ),
    ]
