# Generated by Django 2.2 on 2020-07-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
